# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Build'
  pool:
    vmImage: 'vs2017-win2016' # FIXME this is probably based on an outdated documentation, win19 might work as well
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x86'

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest
      pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Test'
  # Sharing Pipeline artifacts might be needed later on: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  # prefer simple scripts instead of specific tasks if it does work
  - script: docker build -t hosszubalazs/evil_snek .
  - script: docker run hosszubalazs/evil_snek
 # - task: Docker@1
 #   displayName: login
 #   inputs:
 #     containerregistrytype: 'Container Registry'
 #     dockerRegistryEndpoint: 'hosszubalazs_dockerhub'
 #     command: login

# - task: Docker@0
#  displayName: 'Build an image'
#  inputs:
#    containerregistrytype: 'Container Registry'
#    dockerRegistryConnection: 'hosszubalazs_dockerhub'

#  - task: Docker@0
#  displayName: 'Run an image'
#  inputs:
##    containerregistrytype: 'Container Registry'
#    dockerRegistryConnection: 'hosszubalazs_dockerhub'
 #   action: 'Run an image'


# The distribution strategy is not clear
#- job: 'Publish'
#  dependsOn: 'Test'
#  pool:
#    vmImage: 'vs2017-win2016'

  #steps:
#  - task: UsePythonVersion@0
#    inputs:
#     versionSpec: '3.7'
#     architecture: 'x86'

#  - script: python setup.py sdist --format=zip
#    displayName: 'Build sdist'
